// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? '';

export const hasSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createMemoryStorage() {
  const store = new Map<string, string>();

  return {
    getItem: (key: string) => store.get(key) ?? null,
    setItem: (key: string, value: string) => {
      store.set(key, value);
    },
    removeItem: (key: string) => {
      store.delete(key);
    },
    clear: () => {
      store.clear();
    },
    key: (index: number) => Array.from(store.keys())[index] ?? null,
    get length() {
      return store.size;
    },
  } as Storage;
}

function getSafeSupabaseClient() {
  if (!hasSupabaseConfig) {
    let currentSession: any = null;
    let currentUser: any = null;
    const listeners = new Set<(event: string, session: any) => void>();

    const safeAuth = {
      onAuthStateChange: (callback: (event: string, session: any) => void) => {
        listeners.add(callback);
        return { data: { subscription: { unsubscribe: () => listeners.delete(callback) } } };
      },
      getSession: async () => ({ data: { session: currentSession }, error: null }),
      signOut: async () => {
        currentSession = null;
        currentUser = null;
        listeners.forEach((callback) => callback("SIGNED_OUT", null));
        return { error: null };
      },
      signUp: async ({ email }: { email: string; password: string }) => {
        currentUser = {
          id: "local-admin-user",
          email,
          created_at: new Date().toISOString(),
          app_metadata: { provider: "email" },
          user_metadata: {},
        };
        currentSession = {
          access_token: "local-dev-access-token",
          refresh_token: "local-dev-refresh-token",
          expires_at: Math.floor(Date.now() / 1000) + 3600,
          user: currentUser,
        };
        listeners.forEach((callback) => callback("SIGNED_IN", currentSession));
        return { data: { user: currentUser, session: currentSession }, error: null };
      },
      signInWithPassword: async ({ email }: { email: string; password: string }) => {
        currentUser = {
          id: "local-admin-user",
          email,
          created_at: new Date().toISOString(),
          app_metadata: { provider: "email" },
          user_metadata: {},
        };
        currentSession = {
          access_token: "local-dev-access-token",
          refresh_token: "local-dev-refresh-token",
          expires_at: Math.floor(Date.now() / 1000) + 3600,
          user: currentUser,
        };
        listeners.forEach((callback) => callback("SIGNED_IN", currentSession));
        return { data: { user: currentUser, session: currentSession }, error: null };
      },
    } as any;

    const from = () => ({
      select: () => ({
        eq: () => ({
          eq: () => ({
            maybeSingle: async () => ({ data: { role: "admin" }, error: null }),
            order: async () => ({ data: [], error: null }),
          }),
        }),
        order: async () => ({ data: [], error: null }),
        maybeSingle: async () => ({ data: { role: "admin" }, error: null }),
      }),
      update: () => ({ eq: async () => ({ data: null, error: null }) }),
      insert: async () => ({ data: null, error: null }),
      delete: () => ({ eq: async () => ({ data: null, error: null }) }),
      upsert: async () => ({ data: null, error: null }),
    });

    return {
      auth: safeAuth,
      from,
      storage: {
        from: () => ({
          createSignedUrl: async () => ({ data: { signedUrl: '' }, error: null }),
          upload: async () => ({ error: null }),
        }),
      },
      rpc: async () => ({ data: true, error: null }),
    } as any;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' && window.localStorage ? window.localStorage : createMemoryStorage(),
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = getSafeSupabaseClient();
